server:
  port: 8083
  tomcat:
    basedir: /tmp
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 600000
        response-timeout: 60s
      discovery:
        locator:
          enabled: true
      routes:
        - id: tms-web
          uri: lb://tms-web
          predicates:
            - Path=/tms-api/**
          filters:
            - StripPrefix=1
        - id: login-web
          uri: lb://login-web
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
        - id: business-web
          uri: lb://business-web
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
        - id: emp-web
          uri: lb://emp-web
          predicates:
            - Path=/emp-api/**
          filters:
            - StripPrefix=1
        - id: goods-web
          uri: lb://goods-web
          predicates:
            - Path=/goods-api/**
          filters:
            - StripPrefix=1
        - id: activity-web
          uri: lb://activity-web
          predicates:
            - Path=/activity-api/**
          filters:
            - StripPrefix=1
        - id: identify-web
          uri: lb://identify-web
          predicates:
            - Path=/identify/**
          filters:
            - StripPrefix=1
  http:
    multipart:
      max-file-size: 50Mb # 最大支持文件大小
      max-request-size: 1000Mb # 最大支持请求大小
eureka:
  instance:
  #instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 设置微服务调用地址为IP优先（缺省为false）
  #lease-renewal-interval-in-seconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
  #lease-expiration-duration-in-seconds: 15 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    serviceUrl:
      defaultZone: http://hsopecureka.apps.paas-wh-01-uat.taikangcloud.com/eureka/ # 指定服务注册中心的地址

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 1800
